name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout code
        container:
          image: registry.access.redhat.com/ubi8/nodejs-18

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.6.0'

      - name: Update dependencies
        run: npm update

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Release
        id: release_step
        #run: npx semantic-release || echo "No release published"
        run: |
          npx semantic-release > release-log.txt || echo "No release published" > release-log.txt
          # Capture the release notes if a release is published
          if grep -q "Published release" release-log.txt; then
            echo "new_release=true" >> $GITHUB_ENV
            echo "release_notes=$(cat release-log.txt | grep -A 5 "Published release")" >> $GITHUB_ENV
          else
            echo "new_release=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send Email Notification
        if: env.new_release == 'true'  # Send email only if a new release was created
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "UI Library Update - Release ${GITHUB_REF##*/}"
          body: |
            The following changes were included in this release:

            ${{ env.release_notes }}
          to: toota353535@gmail.com
          from: mo.abdallah3535@gmail.com
